@startuml
class DataContext {
    + DataContext(options:DbContextOptions<DataContext>)
    + Articles : DbSet<ArticleEntity>? <<get>> <<set>>
    + ArticleGroups : DbSet<ArticleGroupEntity>? <<get>> <<set>>
    # <<override>> OnModelCreating(modelBuilder:ModelBuilder) : void
}
DbContext <|-- DataContext
@enduml
